### ISSUE TITLE
Comando: lidar_scan.copy()

### ISSUE THREAD

**Issue by JuanSantacoloma** [jmfajardod/pubsub_lidar_husky#1]
Caracteristicas para replicar el error:
**Equipo:**
**- ROS distribution:** Melodic
**- python** : 2.7.17

**Comando en la terminal:**
rosrun pubsub_lidar_husky pubsub_node.py

**Archivo:** scripts/class_pubsub.py 

**Error**
line 33, in Lidar_Callback
    new_msgLaserScan = lidar_scan.copy()
AttributeError: 'LaserScan' object has no attribute 'copy'

**Comment by jmfajardod** [comment]
Fixed by importing numpy and copying the ranges values instead of the whole message. Please pull the new version to apply the changes in your repository (sync repositories), a tutorial about how to make this can be found in: 

https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser
